/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiket.bola;

/**
 *
 * @author Nabila AAP
 */
import javax.swing.*;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.table.*;
public class frame extends javax.swing.JFrame {
    String no_id,nama,jenistiket,harga,banyak,totalbayar,totbayar1;
    int totbayar, harga1, bayar1;
    DefaultTableModel tabMode;
    Connection con;
    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
        setTitle("PEMBELIAN TIKET BOLA");
                Object[] row= {"No.Id","Nama", "Tiket","Harga","Banyak","Total Bayar"};
        tabMode=new DefaultTableModel(null,row);

        jTable1.setModel(tabMode);
        jScrollPane1.getViewport().add(jTable1,null);
    }
    
    public void konekdatabase(){
    try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        con=DriverManager.getConnection("jdbc:odbc:aksestiketbola;uid='admin';pw='admin'");
    }
     catch (Exception e)
        {
            System.err.println("Exception: "+e.getMessage());
        }
    }
    public void hapustabel(){
        int row=tabMode.getRowCount();
        for(int i=0;i<row;i++){
            tabMode.removeRow(0);
        }
    }
    public void tampildataketabel(){
        hapustabel();
        try{
            String sql="Select * from datatiketbola ORDER BY no_id DESC";
            Statement stat=con.createStatement();
            ResultSet set=stat.executeQuery(sql);
            while (set.next()){
                no_id=set.getString("no_id");
                nama=set.getString("nama");
                jenistiket=set.getString("jenistiket");
                harga=set.getString("harga");
                banyak=set.getString("banyak");
                totalbayar=set.getString("totalbayar");
                String[] data={no_id,nama,jenistiket,harga,banyak,totalbayar};
                tabMode.addRow(data);
            }
        }
        catch(Exception e){

        }

    }
    public void simpandata(){

      no_id=txnoid.getText();
      nama=txnama.getText();
      jenistiket=(String)cbtiket.getSelectedItem();
      harga=txharga.getText();
      banyak=txbanyak.getText();
      totalbayar=txbayar.getText();
        try{
            konekdatabase();
            Statement statement=con.createStatement();
            String sql="insert into datatiketbola values ('"+no_id+"','"+nama+ "'," +
                    "'"+jenistiket+"','"+harga+"','"+banyak+"','"+totalbayar+"');";
            statement.executeUpdate(sql);
       statement.close();
    }
        catch (Exception e){

        }

    }
    public void data(){
      no_id=txnoid.getText();
      nama=txnama.getText();
      jenistiket=(String)cbtiket.getSelectedItem();
      harga=txharga.getText();
      banyak=txbanyak.getText();
      totalbayar=txbayar.getText();
    }

    public void hargatiket(){ //create method gajipokok
        int pilihan=cbtiket.getSelectedIndex();
        switch(pilihan){
            case 0:
                txharga.setText("");
            break;
            case 1:
                txharga.setText("75000");
            break;
            case 2:
                txharga.setText("50000");
            break;
            case 3:
                txharga.setText("25000");
            break;
            }
    }

    public void total(){
        harga1=Integer.parseInt(txharga.getText());
        bayar1=Integer.parseInt(txbanyak.getText());
        totbayar=harga1*bayar1;
        DecimalFormat f=new DecimalFormat("#.#");
        totbayar1=String.valueOf(f.format(totbayar));
        txbayar.setText(totbayar1);
    }
    public void bersih(){
        txnoid.setText("");
        txnama.setText("");
        txharga.setText("");
        txbanyak.setText("");
        txbayar.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txbayar = new javax.swing.JTextField();
        txnoid = new javax.swing.JTextField();
        txnama = new javax.swing.JTextField();
        txharga = new javax.swing.JTextField();
        txbanyak = new javax.swing.JTextField();
        cbtiket = new javax.swing.JComboBox<>();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        lihat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("PEMBELIAN TIKET BOLA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 210, 19);

        jLabel2.setText("Total Bayar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 100, 60, 14);

        jLabel3.setText("No. Identitas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 80, 14);

        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 100, 80, 14);

        jLabel5.setText("Jenis Tiket");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 130, 80, 14);

        jLabel6.setText("Harga");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 160, 80, 14);

        jLabel7.setText("Banyak");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 70, 60, 14);
        getContentPane().add(txbayar);
        txbayar.setBounds(320, 100, 150, 20);
        getContentPane().add(txnoid);
        txnoid.setBounds(100, 70, 130, 20);
        getContentPane().add(txnama);
        txnama.setBounds(100, 100, 130, 20);
        getContentPane().add(txharga);
        txharga.setBounds(100, 160, 130, 20);

        txbanyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbanyakActionPerformed(evt);
            }
        });
        getContentPane().add(txbanyak);
        txbanyak.setBounds(320, 70, 150, 20);

        cbtiket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis", "VIP", "Reguler", "Ekonomi" }));
        cbtiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtiketActionPerformed(evt);
            }
        });
        getContentPane().add(cbtiket);
        cbtiket.setBounds(100, 130, 130, 20);

        ubah.setText("Ubah");
        getContentPane().add(ubah);
        ubah.setBounds(320, 160, 70, 23);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(400, 160, 70, 23);

        simpan.setText("Simpan");
        getContentPane().add(simpan);
        simpan.setBounds(320, 130, 70, 23);

        lihat.setText("Lihat");
        getContentPane().add(lihat);
        lihat.setBounds(400, 130, 70, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "no id", "nama", "tiket", "harga", "banyak", "total bayar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 452, 90);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Keluar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Simpan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Ubah");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        jMenuItem4.setText("Hapus");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Lihat Data");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Cari Data");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("About");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(516, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        konekdatabase();
        tampildataketabel();
    }
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        konekdatabase();
        data();
         if(no_id.equals("")||nama.equals("")||jenistiket.equals("Pilih Tiket")||
                 harga.equals("")||banyak.equals("")||totalbayar.equals(""))
         {
             JOptionPane.showMessageDialog(null, "ada data yg belum dimasukkan, periksa kembali!");
         }

        else{
             simpandata();
             bersih();
             tampildataketabel();
             JOptionPane.showMessageDialog(null, "Data sudah masuk. Terima kasih!");
        }
    }
    
    private void cbtiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtiketActionPerformed
        // TODO add your handling code here:
        hargatiket();
        txharga.setEnabled(false);
    }//GEN-LAST:event_cbtiketActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int row=tabMode.getRowCount();
        for(int i=0;i<row;i++){
            tabMode.removeRow(0);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Terima Kasih atas kunjungan anda!");
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        konekdatabase();
        data();
        if(no_id.equals("")||nama.equals("")||jenistiket.equals("Pilih Tiket")||
            harga.equals("")||banyak.equals("")||totalbayar.equals(""))
        {
            JOptionPane.showMessageDialog(null, "ada data yg belum dimasukkan, periksa kembali!");
        }

        else{
            simpandata();
            bersih();
            tampildataketabel();
            JOptionPane.showMessageDialog(null, "Data sudah masuk. Terima kasih!");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        konekdatabase();
        data();
        if(no_id.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Inputkan No.Identitas anda!");
        }

        else{
            try
            {
                Statement statement=con.createStatement();
                String sql="update datatiketbola set nama='"+nama+ "',jenistiket='"+jenistiket+"',harga='"+harga+"',banyak='"
                +banyak+"',totalbayar='"+totalbayar+"' where no_id='"+no_id+"'";
                statement.executeUpdate(sql);
                statement.close();
                con.close();
                JOptionPane.showMessageDialog(null, "Data telah terubah!");

            }
            catch (Exception e)
            {
                System.out.println("Error :"+e);
            }
            simpandata();
            bersih();
            tampildataketabel();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        konekdatabase();
        data();
        try
        {
            String cari=JOptionPane.showInputDialog("Masukkan No Identitas anda");
            Statement statement=con.createStatement();
            String sql="delete from datatiketbola where no_id='"+cari+"'";
            statement.executeUpdate(sql);
            statement.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Data telah terhapus!");

        }
        catch (Exception e)
        {
            System.out.println("Error :"+e);
        }
        bersih();
        tampildataketabel();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        konekdatabase();
        try {
            String cari=JOptionPane.showInputDialog("Masukkan No Identitas anda");
            Statement statement=con.createStatement();
            String sql="select * from datatiketbola where no_id like '"+cari+"'";
            ResultSet rs=statement.executeQuery(sql);
            if(rs.next()) {
                txnoid.setText(rs.getString(1));
                txnama.setText(rs.getString(2));

                cbtiket.setSelectedItem(rs.getString(3));
                txharga.setText(rs.getString(4));
                txbanyak.setText(rs.getString(5));
                txbayar.setText(rs.getString(6));
            } else{
                JOptionPane.showMessageDialog(null, "DATA TIDAK ADA DALAM DATABASE");

            }
            statement.close();
            con.close();
        } catch (Exception ex) {
            System.out.println("Error: "+ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    
    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        konekdatabase();
        bersih();
        tampildataketabel();
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        tentang frm=new tentang();
        frm.show(); 
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void txbanyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbanyakActionPerformed
        // TODO add your handling code here:
        txharga.setEnabled(false);
        total();
    }//GEN-LAST:event_txbanyakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbtiket;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton lihat;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField txbanyak;
    private javax.swing.JTextField txbayar;
    private javax.swing.JTextField txharga;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txnoid;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
